version: "2.1"

services:
  db:
    image: postgres:10.3
    container_name: "qfsd-db-postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "qfsd"
      POSTGRES_PASSWORD: "qfsd"
      POSTGRES_DB: "qfsd"
    volumes:
      - qfsd_db_data:/var/lib/postgresql/data

volumes:
  qfsd_db_data:
    external: true